import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, TextRun } from 'docx';
import { chat, DOCUMENT_SAFETY, NOT_ADVICE } from './ai.js';
import { config } from './config.js';
import { store } from './store.js';
import { search } from './vectors.js';

export type Draft = { title: string; markdown: string; docx: Buffer; sources: string[] };

// Writes a first draft (letter, notice, clause, memo) grounded in the channel's documents.
export async function draftDocument(team: string, channel: string, request: string): Promise<Draft> {
  const hits = await search(team, channel, request);
  const files = [...new Set(hits.map((h) => h.fileName))];
  const sources = hits.map((h) => `<source file="${h.fileName}">\n${h.text}\n</source>`).join('\n\n');
  const system = [
    'You draft legal documents for a law team. Produce a complete, professional first draft.',
    'Use facts (names, dates, clause numbers, amounts) only from the sources and matter brief. Where a fact is missing, insert a placeholder like [CLIENT NAME] instead of inventing it.',
    'Format: first line "# Title", then "## Heading" for sections and plain paragraphs. No commentary before or after the draft.',
    DOCUMENT_SAFETY,
  ].join('\n');
  const user = `Matter brief:\n${(await store.getBrief(channel)) || '(none)'}\n\n${sources || '(no matching documents)'}\n\nDraft this: ${request}`;
  const markdown = await chat(system, user, { maxTokens: config.limits.draftMaxTokens });
  const title = markdown.match(/^#\s+(.+)$/m)?.[1]?.trim() || 'Draft';
  return { title, markdown, docx: await toDocx(title, markdown), sources: files };
}

// Converts the simple heading/paragraph format above into a Word file.
export async function toDocx(title: string, markdown: string): Promise<Buffer> {
  const children: Paragraph[] = [];
  for (const line of markdown.split('\n')) {
    const text = line.trim();
    if (!text) continue;
    if (text.startsWith('# ')) {
      children.push(new Paragraph({ text: text.slice(2), heading: HeadingLevel.TITLE, alignment: AlignmentType.CENTER }));
    } else if (text.startsWith('## ') || text.startsWith('### ')) {
      children.push(new Paragraph({ text: text.replace(/^#+\s*/, ''), heading: HeadingLevel.HEADING_2 }));
    } else if (/^[-*•]\s+/.test(text)) {
      children.push(new Paragraph({ children: runs(text.replace(/^[-*•]\s+/, '')), bullet: { level: 0 } }));
    } else {
      children.push(new Paragraph({ children: runs(text), spacing: { after: 160 } }));
    }
  }
  children.push(
    new Paragraph({
      children: [new TextRun({ text: `DRAFT generated by AI. ${NOT_ADVICE}`, italics: true, size: 18, color: '888888' })],
      spacing: { before: 400 },
    })
  );
  const doc = new Document({ title, sections: [{ children }] });
  return Buffer.from(await Packer.toBuffer(doc));
}

// **bold** spans become bold runs.
function runs(text: string): TextRun[] {
  return text.split(/(\*\*[^*]+\*\*)/).filter(Boolean).map((part) =>
    part.startsWith('**') && part.endsWith('**') ? new TextRun({ text: part.slice(2, -2), bold: true }) : new TextRun(part)
  );
}
